### ISSUE TITLE
GO term and Selected tabs needs a bit more explanation

### ISSUE THREAD

**Issue by lcolladotor** [UMMS-Biocore/debrowser#15]
Hi,

When you run `debrowser` locally and jump to the `GO term` tab without selecting genes, you don't get an error message or any indication that you should have selected some genes under the `Main plots` tab. Similarly for the `Selected` tab.

By the way, there's a tiny typo on the `Main plots` tab. It reads "For mor information;" instead of "For more information;".

Cheers,
Leo

**Comment by nephantes** [comment]
Selected means, literally selected genes with mouse in the main plots. The list go under selected tab. If you change "Choose Dataset" to selected, you can use those selected genes. On the other hand, up and down regulated genes are used in GO term that's why you don't need to do literal selection unless you want to do. By changing padj, foldchange cutoffs you can change up and down regulated gene lists. The list selected in  "Choose Dataset"  drop down will be used in GOTerm tab. So, the default is up+down regulated genes.

**Comment by lcolladotor** [comment]
Ok, thanks for the explanation. Hopefully you can explain this also on the docs, vignette or the app itself. Otherwise I'm sure others will run into the same question I had.
