### ISSUE TITLE
error in uploading file

### ISSUE THREAD

**Issue by MichaelPeibo** [UMMS-Biocore/debrowser#204]
Hi, I am painfully stuck at the first step..

Reporting error `Colnames doesn't match with the metada table`
Here is the link of my count matrix and metainfo, could you help me to check on it?

https://drive.google.com/file/d/1fZHLYVnGXeTmzbdgfwoZmJwb5pXr8qlf/view?usp=sharing
https://drive.google.com/file/d/1gofycjYEC5ctwhnJLqriwyTZAwK3Upd-/view?usp=sharing

Thanks!

**Comment by nephantes** [comment]
The problem is, when you start sample names with numbers, R adds X in front of them. If you put a letter before numbers in the sample names, it should work. 
Second, I also suggest not use - in the sample name rather use _. 
Third, if you want to use  columns while selecting them while choosing conditions, I suggest adding extra columns that include only two conditions/cell type etc in each column. This way, you can use that column while running DE. This will make your condition selections faster otherwise you can always use condition selection boxes to choose them. 
Hope these help.

**Comment by MichaelPeibo** [comment]
@nephantes Great! I rewrite the name and it works!  Thanks!

**Comment by mulchchristina** [comment]
Hey im having a similar problem but the error I get in Rstudio is :
Warning: Error in writeImpl: Text to be written must be a length-one character vector
Any ideas about this error?

**Comment by nephantes** [comment]
you might have some non-numeric characters in your table. You can send me your matrix to support@dolphinnext.com, I can take a look at it.
